import type { VueUiXyConfig } from 'vue-data-ui/vue-ui-xy'

export const alarmChartConfig = {
  devHints: {
    enable: false,
  },
  skeletonConfig: null,
  skeletonDataset: null,
  debug: false,
  theme: '',
  responsive: true,
  loading: false,
  a11y: {
    translations: {
      keyboardNavigation: 'Use the left and right arrow keys to move between data points.',
      tableAvailable: 'A data table for this chart is available below.',
      tableCaption: 'Chart data table',
    },
  },
  events: {
    datapointEnter: null,
    datapointLeave: null,
    datapointClick: null,
  },
  responsiveProportionalSizing: true,
  customPalette: [],
  useCssAnimation: false,
  downsample: {
    threshold: 1500,
  },
  transitions: {
    enable: true,
    pauseOnLoad: true,
    pauseOnDatasetChange: false,
    activationDelayMs: 300,
  },
  chart: {
    fontFamily: 'inherit',
    backgroundColor: '#000000ff',
    color: '#ffffffff',
    height: 600,
    width: 600,
    annotations: [
      {
        show: false,
        yAxis: {
          yTop: null,
          yBottom: null,
          label: {
            text: '',
            textAnchor: 'start',
            position: 'start',
            offsetX: 0,
            offsetY: 0,
            padding: {
              top: 12,
              right: 12,
              bottom: 12,
              left: 12,
            },
            border: {
              stroke: '#FFFFFF',
              strokeWidth: 1,
              rx: 0,
              ry: 0,
            },
            fontSize: 14,
            color: '#2D353C',
            backgroundColor: '#e1e5e8',
          },
          line: {
            stroke: '#2D353C',
            strokeWidth: 1,
            strokeDasharray: 0,
          },
          area: {
            fill: '#e1e5e8',
            opacity: 30,
          },
        },
      },
    ],
    zoom: {
      show: true,
      color: '#CCCCCCff',
      highlightColor: '#4A4A4A',
      fontSize: 14,
      useResetSlot: false,
      startIndex: 0,
      endIndex: 7,
      enableRangeHandles: true,
      enableSelectionDrag: true,
      focusOnDrag: false,
      focusRangeRatio: 0.2,
      maxWidth: 500,
      keepState: false,
      minimap: {
        show: true,
        selectedColor: '#1F77B4',
        selectedColorOpacity: 0.2,
        indicatorColor: '#1A1A1A',
        verticalHandles: false,
        compact: true,
        frameColor: '#CCCCCC',
        additionalHeight: 0,
        handleIconColor: null,
        handleBorderWidth: 1,
        handleBorderColor: null,
        handleFill: null,
        handleWidth: 20,
        handleType: 'grab',
        smooth: false,
        lineColor: '#1A1A1A',
        selectionRadius: 2,
        merged: true,
      },
      preview: {
        enable: true,
        fill: '#CCCCCC50',
        stroke: '#6A6A6Aff',
        strokeWidth: 2,
        strokeDasharray: 0,
      },
      useDefaultFormat: true,
      timeFormat: 'yyyy-MM-dd HH:mm:ss',
      customFormat: null,
    },
    padding: {
      top: 12,
      right: 12,
      bottom: 6,
      left: 6,
    },
    highlighter: {
      color: '#1A1A1Aff',
      opacity: 5,
      useLine: false,
      lineDasharray: 2,
      lineWidth: 1,
      crosshairs: {
        show: false,
        stroke: '#2D353Cff',
        strokeWidth: 1,
        strokeDasharray: 3,
        stopOnPoint: false,
        dot: {
          radius: 2,
          fill: '#2D353C',
          stroke: '#FFFFFFff',
          strokeWidth: 1,
        },
      },
    },
    highlightArea: {
      show: false,
      from: 0,
      to: 0,
      color: '#CCCCCCff',
      opacity: 20,
      caption: {
        text: 'Caption',
        fontSize: 20,
        color: '#1A1A1Aff',
        bold: false,
        offsetY: 0,
        width: 'auto',
        padding: 3,
        textAlign: 'center',
      },
    },
    timeTag: {
      show: false,
      backgroundColor: '#e1e5e8ff',
      color: '#ffffffff',
      fontSize: 12,
      circleMarker: {
        radius: 3,
        color: '#1A1A1Aff',
      },
      useDefaultFormat: true,
      timeFormat: 'yyyy-MM-dd HH:mm:ss',
      customFormat: null,
    },
    grid: {
      stroke: '#e1e5e8ff',
      showVerticalLines: false,
      showHorizontalLines: false,
      position: 'middle',
      frame: {
        show: false,
        stroke: '#E1E5E8ff',
        strokeWidth: 2,
        strokeLinecap: 'round',
        strokeLinejoin: 'round',
        strokeDasharray: 0,
      },
      labels: {
        show: true,
        color: '#ffffffff',
        fontSize: 16,
        axis: {
          yLabel: '',
          yLabelOffsetX: 0,
          xLabel: '',
          xLabelOffsetY: 0,
          fontSize: 12,
        },
        zeroLine: {
          show: true,
        },
        xAxis: {
          showBaseline: true,
          showCrosshairs: true,
          crosshairsAlwaysAtZero: false,
          crosshairSize: 6,
          commonScaleSteps: 10,
          useNiceScale: true,
          scaleMin: null,
          scaleMax: null,
          rounding: 1,
          formatter: null,
          reverse: false,
        },
        yAxis: {
          reverse: false,
          position: 'left',
          showBaseline: true,
          showCrosshairs: true,
          crosshairSize: 6,
          commonScaleSteps: 10,
          useIndividualScale: false,
          useNiceScale: true,
          stacked: false,
          gap: 12,
          labelWidth: 40,
          formatter: null,
          scaleMin: null,
          scaleMax: null,
          groupColor: 'rgba(255, 255, 255, 1)',
          scaleLabelOffsetX: 0,
          scaleValueOffsetX: 0,
          rounding: 1,
          serieNameFormatter: null,
        },
        xAxisLabels: {
          color: '#ffffffff',
          show: true,
          values: [
            '1月',
            '2月',
            '3月',
            '4月',
            '5月',
            '6月',
            '7月',
            '8月',
            '9月',
            '10月',
            '11月',
            '12月',
          ],
          datetimeFormatter: {
            enable: false,
            locale: 'en',
            useUTC: false,
            januaryAsYear: false,
            options: {
              year: 'yyyy',
              month: "MMM 'yy",
              day: 'dd MMM',
              hour: 'HH:mm',
              minute: 'HH:mm:ss',
              second: 'HH:mm:ss',
            },
          },
          fontSize: 18,
          showOnlyFirstAndLast: false,
          showOnlyAtModulo: false,
          modulo: 12,
          yOffset: 8,
          rotation: 0,
          autoRotate: {
            enable: true,
            angle: -30,
          },
        },
      },
    },
    comments: {
      show: true,
      showInTooltip: true,
      width: 200,
      offsetX: 0,
      offsetY: 0,
    },
    labels: {
      fontSize: 16,
      prefix: '',
      suffix: '',
    },
    legend: {
      color: '#ffffffff',
      show: true,
      fontSize: 16,
      position: 'bottom',
      selectAllToggle: {
        show: false,
        backgroundColor: '#E1E5E8ff',
        color: '#ffffffff',
      },
    },
    title: {
      text: '',
      color: '#1A1A1Aff',
      fontSize: 20,
      bold: true,
      textAlign: 'center',
      paddingLeft: 0,
      paddingRight: 0,
      subtitle: {
        color: '#CCCCCCff',
        text: '',
        fontSize: 16,
        bold: false,
      },
      show: false,
    },
    tooltip: {
      show: true,
      color: '#1A1A1Aff',
      backgroundColor: '#FFFFFFff',
      fontSize: 14,
      customFormat: null,
      borderRadius: 4,
      borderColor: '#e1e5e8',
      borderWidth: 1,
      backgroundOpacity: 30,
      position: 'center',
      offsetX: 0,
      offsetY: 24,
      smooth: true,
      backdropFilter: true,
      smoothForce: 0.18,
      smoothSnapThreshold: 0.25,
      teleportTo: 'body',
      showTimeLabel: true,
      showValue: true,
      showPercentage: false,
      roundingValue: 0,
      roundingPercentage: 0,
      useDefaultTimeFormat: true,
      timeFormat: 'yyyy-MM-dd HH:mm:ss',
    },
    userOptions: {
      show: true,
      showOnChartHover: false,
      keepStateOnChartLeave: true,
      position: 'right',
      buttons: {
        tooltip: true,
        pdf: true,
        csv: true,
        img: true,
        table: true,
        labels: true,
        fullscreen: true,
        sort: false,
        stack: true,
        animation: false,
        annotator: true,
        svg: true,
        zoom: false,
        altCopy: false,
      },
      callbacks: {
        animation: null,
        annotator: null,
        csv: null,
        fullscreen: null,
        img: null,
        labels: null,
        pdf: null,
        sort: null,
        stack: null,
        table: null,
        tooltip: null,
        svg: null,
        zoom: null,
        altCopy: null,
      },
      buttonTitles: {
        open: 'Open options',
        close: 'Close options',
        tooltip: 'Toggle tooltip',
        pdf: 'Download PDF',
        csv: 'Download CSV',
        img: 'Download PNG',
        table: 'Toggle table',
        labels: 'Toggle labels',
        fullscreen: 'Toggle fullscreen',
        stack: 'Toggle stack mode',
        annotator: 'Toggle annotator',
        svg: 'Download SVG',
        altCopy: 'Copy alt text',
      },
      print: {
        scale: 2,
        orientation: 'auto',
        overflowTolerance: 0.2,
      },
      useCursorPointer: false,
    },
  },
  bar: {
    showTransition: true,
    transitionDurationMs: 300,
    borderRadius: 2,
    useGradient: true,
    periodGap: 0.1,
    innerGap: 0,
    border: {
      useSerieColor: false,
      strokeWidth: 1,
      stroke: '#FFFFFFff',
    },
    labels: {
      show: true,
      offsetY: -8,
      offsetX: 0,
      rotation: 0,
      textAnchor: null,
      alwaysOnTop: false,
      rounding: 0,
      color: '#1A1A1Aff',
      formatter: null,
    },
    serieName: {
      show: false,
      offsetY: -6,
      useAbbreviation: true,
      abbreviationSize: 3,
      useSerieColor: true,
      color: '#1A1A1Aff',
      bold: false,
    },
  },
  line: {
    showTransition: true,
    transitionDurationMs: 300,
    radius: 6,
    useGradient: false,
    strokeWidth: 2,
    cutNullValues: false,
    interLine: {
      pairs: [],
      colors: [],
      fillOpacity: 0.25,
    },
    dot: {
      selectedRadius: 4.5,
      hideAboveMaxSerieLength: 62,
      useSerieColor: false,
      fill: '#FFFFFF',
      strokeWidth: 2,
    },
    labels: {
      show: true,
      offsetY: -16,
      offsetX: 0,
      rotation: 0,
      rounding: 0,
      color: '#1A1A1Aff',
      formatter: null,
      textAnchor: null,
      alwaysOnTop: false,
    },
    area: {
      useGradient: true,
      opacity: 20,
    },
    tag: {
      followValue: true,
      formatter: null,
      fontSize: 14,
    },
  },
  plot: {
    showTransition: true,
    transitionDurationMs: 300,
    radius: 6,
    useGradient: true,
    dot: {
      useSerieColor: true,
      fill: '#FFFFFF',
      strokeWidth: 0.5,
    },
    labels: {
      show: true,
      offsetY: -8,
      offsetX: 0,
      rotation: 0,
      rounding: 0,
      color: '#1A1A1Aff',
      formatter: null,
      textAnchor: null,
      alwaysOnTop: false,
    },
    tag: {
      followValue: true,
      formatter: null,
      fontSize: 14,
    },
  },
  table: {
    useDialog: false,
    responsiveBreakpoint: 400,
    rounding: 0,
    sparkline: true,
    showSum: true,
    columnNames: {
      period: 'Period',
      total: 'Total',
    },
    th: {
      backgroundColor: '#FAFAFAff',
      color: '#1A1A1Aff',
      outline: '',
    },
    td: {
      backgroundColor: '#FAFAFAff',
      color: '#1A1A1Aff',
      outline: '',
    },
    useDefaultTimeFormat: true,
    timeFormat: 'yyyy-MM-dd HH:mm:ss',
  },
  showTable: false,
} as VueUiXyConfig
