import type { VueUiHorizontalBarConfig } from 'vue-data-ui/vue-ui-horizontal-bar'

export const operationChartConfig: VueUiHorizontalBarConfig = {
  skeletonDataset: null,
  skeletonConfig: null,
  debug: false,
  loading: false,
  autoSize: true,
  responsive: false,
  theme: '',
  customPalette: [],
  useCssAnimation: true,
  a11y: {
    translations: {
      keyboardNavigation:
        'Use the left and right, or up and down arrow keys to move between datapoints',
      tableAvailable: 'A data table for this chart is available below.',
      tableCaption: 'Chart data table',
    },
  },
  events: {
    datapointEnter: null,
    datapointLeave: null,
    datapointClick: null,
  },
  style: {
    fontFamily: 'inherit',
    chart: {
      backgroundColor: '#FFFFFFff',
      color: '#1A1A1Aff',
      width: 512,
      height: 316,
      layout: {
        bars: {
          rowColor: '#FFFFFF00',
          rowRadius: 4,
          sort: 'desc',
          useStroke: false,
          strokeWidth: 2,
          height: 32,
          gap: 6,
          borderRadius: 4,
          offsetX: 12,
          paddingRight: 0,
          useGradient: true,
          gradientIntensity: 20,
          fillOpacity: 90,
          underlayerColor: '#FFFFFF',
          dataLabels: {
            color: '#1A1A1Aff',
            bold: true,
            fontSize: 12,
            value: {
              show: true,
              roundingValue: 0,
              prefix: '',
              suffix: '',
              formatter: null,
            },
            percentage: {
              show: false,
              roundingPercentage: 0,
            },
            offsetX: 0,
          },
          nameLabels: {
            show: true,
            color: '#1A1A1Aff',
            bold: false,
            fontSize: 10,
            offsetX: 0,
          },
          parentLabels: {
            show: true,
            color: '#1A1A1Aff',
            bold: false,
            fontSize: 10,
            offsetX: 0,
            paddingBottom: 0,
          },
        },
        highlighter: {
          color: '#1A1A1Aff',
          opacity: 5,
        },
        separators: {
          show: true,
          color: '#e1e5e8ff',
          strokeWidth: 1,
          fullWidth: true,
        },
      },
      title: {
        text: '',
        color: '#1A1A1Aff',
        fontSize: 20,
        bold: true,
        textAlign: 'center',
        paddingLeft: 0,
        paddingRight: 0,
        subtitle: {
          color: '#A1A1A1ff',
          text: '',
          fontSize: 16,
          bold: false,
        },
      },
      legend: {
        show: true,
        bold: true,
        backgroundColor: '#FFFFFFff',
        color: '#1A1A1Aff',
        fontSize: 14,
        selectAllToggle: {
          show: false,
          backgroundColor: '#E1E5E8ff',
          color: '#1A1A1Aff',
        },
        position: 'top',
        roundingValue: 0,
        roundingPercentage: 0,
        prefix: '',
        suffix: '',
        showValue: false,
      },
      tooltip: {
        show: true,
        color: '#1A1A1Aff',
        backgroundColor: '#FFFFFFff',
        fontSize: 14,
        customFormat: null,
        borderRadius: 4,
        borderColor: '#e1e5e8',
        borderWidth: 1,
        backgroundOpacity: 30,
        position: 'center',
        offsetX: 0,
        offsetY: 24,
        smooth: true,
        backdropFilter: true,
        smoothForce: 0.18,
        smoothSnapThreshold: 0.25,
        teleportTo: 'body',
        showValue: true,
        showPercentage: true,
        roundingValue: 0,
        roundingPercentage: 0,
        prefix: '',
        suffix: '',
      },
    },
  },
  userOptions: {
    show: true,
    showOnChartHover: true,
    keepStateOnChartLeave: true,
    position: 'right',
    buttons: {
      tooltip: true,
      pdf: true,
      csv: true,
      img: true,
      table: true,
      labels: false,
      fullscreen: true,
      sort: true,
      stack: false,
      animation: false,
      annotator: true,
      svg: true,
      zoom: false,
      altCopy: false,
    },
    callbacks: {
      animation: null,
      annotator: null,
      csv: null,
      fullscreen: null,
      img: null,
      labels: null,
      pdf: null,
      sort: null,
      stack: null,
      table: null,
      tooltip: null,
      svg: null,
      zoom: null,
      altCopy: null,
    },
    buttonTitles: {
      open: 'Open options',
      close: 'Close options',
      tooltip: 'Toggle tooltip',
      pdf: 'Download PDF',
      csv: 'Download CSV',
      img: 'Download PNG',
      table: 'Toggle table',
      fullscreen: 'Toggle fullscreen',
      sort: 'Toggle sort',
      annotator: 'Toggle annotator',
      svg: 'Download SVG',
      altCopy: 'Copy alt text',
    },
    print: {
      scale: 2,
      orientation: 'auto',
      overflowTolerance: 0.2,
    },
    useCursorPointer: false,
  },
  table: {
    show: false,
    responsiveBreakpoint: 400,
    useDialog: false,
    th: {
      backgroundColor: '#FFFFFFff',
      color: '#1A1A1Aff',
      outline: 'none',
    },
    td: {
      backgroundColor: '#FFFFFFff',
      color: '#1A1A1Aff',
      outline: 'none',
      roundingValue: 0,
      roundingPercentage: 0,
      prefix: '',
      suffix: '',
    },
  },
  translations: {
    parentName: 'Group',
    childName: 'Serie',
    value: '线路长度',
    percentageToTotal: '百分比',
    percentageToSerie: '% / group',
  },
}
